language: node_js
node_js: "10"

addons:
  apt:
    packages:
      - xvfb
      - libcairo2-dev
      - libpango1.0-dev
      - libjpeg-dev
      - libgif-dev
      - librsvg2-dev
  homebrew:
    packages:
      - pkg-config
      - cairo
      - pango
      - libpng
      - jpeg
      - giflib
      - librsvg

matrix:
  include:
    - if: branch =~ /v\d+\.\d+\.\d+/
      os: windows
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install:
        - choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo --allow-empty-checksums
        - curl -LO http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip
        - 7z x gtk+-bundle_2.22.1-20101229_win64.zip -y -o/c/GTK
      script:
        - npm run dist:win
    - if: branch =~ /v\d+\.\d+\.\d+/
      os: osx
      osx_image: xcode11.3
      script:
        - npm run dist:mac
    - if: branch =~ /v\d+\.\d+\.\d+/
      os: linux
      script:
        - npm run dist:linux
    - if: branch = master
      os: linux
      before_install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install -g xvfb-maybe
      script:
        - npm run lint
        - npm run build
        - xvfb-maybe npm run e2e

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
    - .next/cache

install:
  - npm ci

before_script:
  - if [[ "$TRAVIS_TAG" != "" ]]; then npm --no-git-tag-version version ${TRAVIS_TAG:1}; fi
